export const GET_DETAILCOURSE_REQUEST = 'CoursesReducer/GET_DETAILCOURSE_REQUEST';
export const GET_DETAILCOURSE_SUCCESS = 'CoursesReducer/GET_DETAILCOURSE_SUCCESS';
export const GET_DETAILCOURSE_FAILED = 'CoursesReducer/GET_DETAILCOURSE_FAILED';