export const GET_DETAILCOURSE_REQUEST = 'CoursesReducer/GET_DETAILCOURSE_REQUEST';
export const GET_DETAILCOURSE_SUCCESS = 'CoursesReducer/GET_DETAILCOURSE_SUCCESS';
export const GET_DETAILCOURSE_FAILED = 'CoursesReducer/GET_DETAILCOURSE_FAILED';
export const REGISTER_COURSE_REUQEST = 'CoursesReducer/REGISTER_COURSE_REUQEST';
export const REGISTER_COURSE_SUCCESS = 'CoursesReducer/REGISTER_COURSE_SUCCESS';
export const REGISTER_COURSE_FAILED = 'CoursesReducer/REGISTER_COURSE_FAILED';